server.port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6547/payment
    username: payment
    password: 12345
    driver-class-name: org.postgresql.Driver

pricing:
  nds-rate: 0.10