server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6547/payment
    username: payment
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate.format_sql: true
        hibernate.show_sql: true

pricing:
  nds-rate: 0.10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    ru.practicum.payment.feign.client: DEBUG